### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi#2]
Can the following readme be added to the repo or an external link provided? 

https://github.com/Azure-Samples/Custom-vision-service-iot-edge-raspberry-pi/blob/397d17e0d536ae972b76b43caea47f6b0e9070f7/modules/ImageClassifierService/readme.txt#L25

**Comment by emmanuel-bv** [comment]
Hello,

I removed the pointer to AzureML since this sample does not use AzureML. If you want to learn more about how to use CustomVision with AzureML, you can go to the CustomVision website (free), create a small project, export it as a docker container and in the downloaded zip file you will get all the instructions to use CustomVision with AzureML.
